name: CI Checks

on: [push]

jobs:
  test-lint:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Start Containers
        run: docker compose build

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Linting
        run: docker compose run --rm app python -m flake8 /app
